# Prometheus 配置文件 - 博客系统监控
# 适用于 Next.js 15.3.5+ & React 19.1.0+ 应用程序监控

global:
  # 全局抓取间隔
  scrape_interval: 15s
  
  # 评估规则的间隔
  evaluation_interval: 15s
  
  # 外部标签，用于标识此 Prometheus 实例
  external_labels:
    cluster: 'blog-production'
    environment: 'production'
    instance: 'blog-prometheus'

# 规则文件配置
rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # Node.js 应用程序监控
  - job_name: 'blog-app'
    static_configs:
      - targets: ['localhost:3000']
    scrape_interval: 10s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    
    # 添加自定义标签
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:3000
    
    # 指标重命名
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nodejs_(.+)'
        target_label: __name__
        replacement: 'blog_nodejs_${1}'

  # Node Exporter (系统指标)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s
    
    # 过滤不需要的指标
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'node_textfile_scrape_error'
        action: drop

  # Docker 容器监控 (如果使用 Docker)
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 15s
    metrics_path: /metrics

  # Nginx 监控 (如果使用 Nginx)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
    scrape_interval: 15s
    
  # Redis 监控 (如果使用 Redis)
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 15s

  # PostgreSQL 监控 (如果使用数据库)
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Blackbox 监控 (外部健康检查)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:3000
        - http://localhost:3000/api/health
        - http://localhost:3000/sitemap.xml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # SSL 证书监控
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [ssl_expiry]
    static_configs:
      - targets:
        - https://yourdomain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # DNS 监控
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns_udp]
    static_configs:
      - targets:
        - yourdomain.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  # 自定义应用程序指标
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['localhost:3001']
    scrape_interval: 30s
    metrics_path: /custom-metrics
    
    # 仅在指标存在时抓取
    honor_labels: true
    
# 存储配置
storage:
  tsdb:
    # 数据保留时间
    retention.time: 30d
    
    # 数据保留大小
    retention.size: 10GB
    
    # 数据压缩
    wal-compression: true

# 远程写入配置 (可选，用于长期存储)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       batch_send_deadline: 5s
#       min_shards: 1
#       max_shards: 10

# 远程读取配置 (可选)
# remote_read:
#   - url: "http://cortex:9009/api/prom/read"

# 服务发现配置 (用于动态环境)
# scrape_configs:
#   - job_name: 'kubernetes-pods'
#     kubernetes_sd_configs:
#       - role: pod
#     relabel_configs:
#       - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#         action: keep
#         regex: true

# 联邦配置 (用于多 Prometheus 实例)
# scrape_configs:
#   - job_name: 'federate'
#     scrape_interval: 15s
#     honor_labels: true
#     metrics_path: '/federate'
#     params:
#       'match[]':
#         - '{job=~"prometheus|node.*"}'
#     static_configs:
#       - targets:
#         - 'prometheus-remote:9090'